kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: user1
  name: camel-quarkus-fruits-persist
spec:
  replicas: 0
  selector:
    matchLabels:
      app: camel-quarkus-fruits-persist
  template:
    metadata:
      labels:
        app: camel-quarkus-fruits-persist
        deployment: camel-quarkus-fruits-persist
    spec:
      containers:
        - name: camel-quarkus-fruits-persist
          image: ''
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          env:
            - name: QUARKUS_BROKER_URL
              value: 'tcp://ex-aao-hdls-svc.user1.svc.cluster.local:61616'
          resources: {}